<?php 

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) exit;

return apply_filters(
    'bs_slider_option',
    array(
        'animation'         => 'slide',
        'cards_border'      => 20,
        'cube_shadows'      => 'yes',
        'cube_slide_shadows'    => 'yes',
        'cube_shadowoffset'     => 20,
        'cube_shadowScale'  => 1,
        'navigation_arrow_style'    => 'style1',
        'arrow_font_size'   => 16,
        'arrow_color'   => '#ffffff',
        'arrow_hover_color'     => '#ffffff',
        'arrow_bg_color'    => '#ffffff',
        'arrow_hover_bg_color'  => '#333333',
        'arrow_border_color'    => '#ffffff',
        'arrow_position_unit'   => 'px',
        'arrow_position_top'    => 220,
        'arrow_position_bottom'     => '',
        'arrow_position_left'   => 10,
        'arrow_position_right'  => 10,
        'pagination_type'   => 'bullets',
        'bullets_navigation_style'  => 'style1',
        'bullets_bg_color'  => '',
        'bullets_hover_bg_color'    => '#ffffff',
        'bullets_border_color'  => '#ffffff',
        'fraction_navigation_style'     => 'style1',
        'fraction_color'    => '#ff0000',
        'fraction_font_size'    => 16,
        'fraction_position'     => 'center',
        'control_progress_bar'  => 'no',
        'progress_bar_position'     => 'bottom',
        'progress_bar_color'    => '#ff0000',
        'custom_navigation_style'   => 'style1',
        'custom_text_color'     => '#ffffff',
        'custom_background_color'   => '#007aff',
        'custom_active_text_color'  => '#ffffff',
        'custom_active_background_color'    => '#0a0607',
        'control_enable_responsive'     => 'no',
        'items_in_desktop'  => 4,
        'items_in_tablet'   => 2,
        'items_in_mobile'   => 1,
        'slide_control_view_auto'   => 'no',
        'control_autoplay'  => 'no',
        'autoplay_timing'   => 3000,
        'control_autoplay_timeleft'     => 'no',
        'control_autoplay_timeleft_color'   => '#007aff',
        'control_autoplay_timeleft_position'    => 'bottom-right',
        'control_scrollbar'     => 'no',
        'scrollbar_position'    => 'bottom',
        'scrollbar_color'   => '#999999',
        'image_unit'    => 'px',
        'width_image'   => 700,
        'height_image'  => 400,
        'control_slider_vertical'   => 'no',
        'control_lazyload_images'   => 'no',
        'control_grab_cursor'   => 'no',
        'control_rewind'    => 'no',
        'control_slide_space'   => 10,
        'control_loop_slider'   => 'no',
        'control_slide_speed'   => 400,
        'zoom_images'   => 'no',
        'control_keyboard'  => 'no',
        'control_mousewheel'    => 'no',
        'control_rtl_slider'    => 'no',
        'enable_grid_layout'    => 'no',
        'grid_layout_axis'  => 'row',
        'grid_count'    => 2,
        'enable_slides_group'   => 'no',
        'slides_per_group'  => 1,
    )
);